---
baseURL: https://nicholaswilde.github.io/
languageCode: en-us
title: Nicholas Wilde
theme: "toha"
googleAnalytics: "G-Z2DZJYE1MB"
enableRobotsTXT: true
enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  gitRepo: https://github.com/nicholaswilde/nicholaswilde.github.io
  background: images/background.jpg
  logo:
    favicon: images/favicon.jpg
  enableTOC: true
  enableBlogPost: false
  newsletter:
    enable: false
