---
version: '3'

tasks:
  install:
    desc: Install hugo
    cmds:
      - brew install hugo
  serve:
    desc: Start the hugo server
    cmds:
      - hugo server --theme toha --watch --bind=0.0.0.0
  default:
    cmds:
      - task -l
    silent: true
