---
version: '3'

tasks:
  install:
    desc: Install hugo
    cmds:
      - brew install hugo
  update:
    desc: Update docker image
    cmds:
      - docker pull hugomods/hugo
  serve:
    desc: Start the hugo server using a Docker image
    cmds:
      - docker run -it --rm -v "${PWD}":/src hugomods/hugo server -w
  serve-local:
    desc: Start the hugo server using local installation
    cmds:
      - hugo server --watch
  deps:
    desc: Install theme
    cmds:
      - hugo mod get -u github.com/hugo-toha/toha/v4
  default:
    cmds:
      - task -l
    silent: true
